TRACKING_AREAS = {
    "bay_area": {
        "title": "Bay Area",
        "description": "Including Zip Codes: 94116, 94131, 94132, 94127, 94112, 94134, 94015, 94014, 94005, 94080, 94044, 94066, 94128, 94030, 94010, 94401, 94404, 94403, 94402",
        "listing": [
            {
                "zip_code": 94116,
                "base_url": "https://www.zillow.com/san-francisco-ca-94116/?searchQueryState=",
                "search_query": {
                    "usersSearchTerm": "",
                    "mapBounds": {
                        "north": 37.754831,
                        "east": -122.458712,
                        "south": 37.733698,
                        "west": -122.508187,
                    },
                    "mapZoom": 15,
                    "isMapVisible": True,
                    "filterState": {
                        "price": {"min": 0, "max": 1250000},
                        "doz": {"value": "7"},
                        "con": {"value": False},
                        "apa": {"value": False},
                        "mp": {"min": 0, "max": 6774},
                        "ah": {"value": True},
                        "sort": {"value": "globalrelevanceex"},
                        "land": {"value": False},
                        "tow": {"value": False},
                        "manu": {"value": False},
                        "apco": {"value": False},
                    },
                    "isListVisible": True,
                    "regionSelection": [{"regionId": 97570, "regionType": 7}],
                    "pagination": {},
                },
            },
            {
                "zip_code": 94131,
                "base_url": "https://www.zillow.com/san-francisco-ca-94131/?searchQueryState=",
                "search_query": {
                    "usersSearchTerm": "",
                    "mapBounds": {
                        "north": 37.77337603460887,
                        "east": -122.39373304724121,
                        "south": 37.71887724604914,
                        "west": -122.49415495275879,
                    },
                    "mapZoom": 14,
                    "isMapVisible": True,
                    "filterState": {
                        "price": {"min": 0, "max": 1250000},
                        "doz": {"value": "7"},
                        "con": {"value": False},
                        "apa": {"value": False},
                        "mp": {"min": 0, "max": 6774},
                        "ah": {"value": True},
                        "sort": {"value": "globalrelevanceex"},
                        "land": {"value": False},
                        "tow": {"value": False},
                        "manu": {"value": False},
                        "apco": {"value": False},
                    },
                    "isListVisible": True,
                    "regionSelection": [{"regionId": 97585, "regionType": 7}],
                    "pagination": {},
                },
            },
            {
                "zip_code": 94132,
                "base_url": "https://www.zillow.com/san-francisco-ca-94132/?searchQueryState=",
                "search_query": {
                    "usersSearchTerm": "",
                    "mapBounds": {
                        "north": 37.75584217911687,
                        "east": -122.4358340472412,
                        "south": 37.70133047674069,
                        "west": -122.53625595275878,
                    },
                    "mapZoom": 14,
                    "isMapVisible": True,
                    "filterState": {
                        "price": {"min": 0, "max": 1250000},
                        "doz": {"value": "7"},
                        "con": {"value": False},
                        "apa": {"value": False},
                        "mp": {"min": 0, "max": 6774},
                        "ah": {"value": True},
                        "sort": {"value": "globalrelevanceex"},
                        "land": {"value": False},
                        "tow": {"value": False},
                        "manu": {"value": False},
                        "apco": {"value": False},
                    },
                    "isListVisible": True,
                    "regionSelection": [{"regionId": 97586, "regionType": 7}],
                    "pagination": {},
                },
            },
            {
                "zip_code": 94127,
                "base_url": "https://www.zillow.com/san-francisco-ca-94127/?searchQueryState=",
                "search_query": {
                    "usersSearchTerm": "",
                    "mapBounds": {
                        "north": 37.748056203817896,
                        "east": -122.43218602362062,
                        "south": 37.7208025015759,
                        "west": -122.4823969763794,
                    },
                    "mapZoom": 15,
                    "isMapVisible": True,
                    "filterState": {
                        "price": {"min": 0, "max": 1250000},
                        "doz": {"value": "7"},
                        "con": {"value": False},
                        "apa": {"value": False},
                        "mp": {"min": 0, "max": 6774},
                        "ah": {"value": True},
                        "sort": {"value": "globalrelevanceex"},
                        "land": {"value": False},
                        "tow": {"value": False},
                        "manu": {"value": False},
                        "apco": {"value": False},
                    },
                    "isListVisible": True,
                    "regionSelection": [{"regionId": 97581, "regionType": 7}],
                    "pagination": {},
                },
            },
            {
                "zip_code": 94112,
                "base_url": "https://www.zillow.com/san-francisco-ca-94112/?searchQueryState=",
                "search_query": {
                    "usersSearchTerm": "",
                    "mapBounds": {
                        "north": 37.74916058914758,
                        "east": -122.3914230472412,
                        "south": 37.69464396707489,
                        "west": -122.49184495275878,
                    },
                    "mapZoom": 14,
                    "isMapVisible": True,
                    "filterState": {
                        "price": {"min": 0, "max": 1250000},
                        "doz": {"value": "7"},
                        "con": {"value": False},
                        "apa": {"value": False},
                        "mp": {"min": 0, "max": 6774},
                        "ah": {"value": True},
                        "sort": {"value": "globalrelevanceex"},
                        "land": {"value": False},
                        "tow": {"value": False},
                        "manu": {"value": False},
                        "apco": {"value": False},
                    },
                    "isListVisible": True,
                    "regionSelection": [{"regionId": 97567, "regionType": 7}],
                    "pagination": {},
                },
            },
            {
                "zip_code": 94134,
                "base_url": "https://www.zillow.com/san-francisco-ca-94134/?searchQueryState=",
                "search_query": {
                    "usersSearchTerm": "",
                    "mapBounds": {
                        "north": 37.74927803667809,
                        "east": -122.3580900472412,
                        "south": 37.69476150107636,
                        "west": -122.45851195275878,
                    },
                    "mapZoom": 14,
                    "isMapVisible": True,
                    "filterState": {
                        "price": {"min": 0, "max": 1250000},
                        "doz": {"value": "7"},
                        "con": {"value": False},
                        "apa": {"value": False},
                        "mp": {"min": 0, "max": 6774},
                        "ah": {"value": True},
                        "sort": {"value": "globalrelevanceex"},
                        "land": {"value": False},
                        "tow": {"value": False},
                        "manu": {"value": False},
                        "apco": {"value": False},
                    },
                    "isListVisible": True,
                    "regionSelection": [{"regionId": 97588, "regionType": 7}],
                    "pagination": {},
                },
            },
            {
                "zip_code": 94015,
                "base_url": "https://www.zillow.com/daly-city-ca-94015/?searchQueryState=",
                "search_query": {
                    "usersSearchTerm": "",
                    "mapBounds": {
                        "north": 37.733845602847936,
                        "east": -122.37621159448243,
                        "south": 37.62474970367207,
                        "west": -122.57705540551758,
                    },
                    "mapZoom": 13,
                    "isMapVisible": True,
                    "filterState": {
                        "price": {"min": 0, "max": 1250000},
                        "doz": {"value": "7"},
                        "con": {"value": False},
                        "apa": {"value": False},
                        "mp": {"min": 0, "max": 6774},
                        "ah": {"value": True},
                        "sort": {"value": "globalrelevanceex"},
                        "land": {"value": False},
                        "tow": {"value": False},
                        "manu": {"value": False},
                        "apco": {"value": False},
                    },
                    "isListVisible": True,
                    "regionSelection": [{"regionId": 97506, "regionType": 7}],
                    "pagination": {},
                },
            },
            {
                "zip_code": 94014,
                "base_url": "https://www.zillow.com/daly-city-ca-94014/?searchQueryState=",
                "search_query": {
                    "usersSearchTerm": "",
                    "mapBounds": {
                        "north": 37.7145177189827,
                        "east": -122.3882155472412,
                        "south": 37.659975601049595,
                        "west": -122.48863745275878,
                    },
                    "mapZoom": 14,
                    "isMapVisible": True,
                    "filterState": {
                        "price": {"min": 0, "max": 1250000},
                        "doz": {"value": "7"},
                        "con": {"value": False},
                        "apa": {"value": False},
                        "mp": {"min": 0, "max": 6774},
                        "ah": {"value": True},
                        "sort": {"value": "globalrelevanceex"},
                        "land": {"value": False},
                        "tow": {"value": False},
                        "manu": {"value": False},
                        "apco": {"value": False},
                    },
                    "isListVisible": True,
                    "regionSelection": [{"regionId": 97505, "regionType": 7}],
                    "pagination": {},
                },
            },
            {
                "zip_code": 94005,
                "base_url": "https://www.zillow.com/brisbane-ca-94005/?searchQueryState=",
                "search_query": {
                    "usersSearchTerm": "",
                    "mapBounds": {
                        "north": 37.71672975890848,
                        "east": -122.36844654724122,
                        "south": 37.66218926835778,
                        "west": -122.4688684527588,
                    },
                    "mapZoom": 14,
                    "isMapVisible": True,
                    "filterState": {
                        "price": {"min": 0, "max": 1250000},
                        "doz": {"value": "7"},
                        "con": {"value": False},
                        "apa": {"value": False},
                        "mp": {"min": 0, "max": 6774},
                        "ah": {"value": True},
                        "sort": {"value": "globalrelevanceex"},
                        "land": {"value": False},
                        "tow": {"value": False},
                        "manu": {"value": False},
                        "apco": {"value": False},
                    },
                    "isListVisible": True,
                    "regionSelection": [{"regionId": 97500, "regionType": 7}],
                    "pagination": {},
                },
            },
            {
                "zip_code": 94080,
                "base_url": "https://www.zillow.com/south-san-francisco-ca-94080/?searchQueryState=",
                "search_query": {
                    "pagination": {},
                    "usersSearchTerm": "",
                    "mapBounds": {
                        "north": 37.6837882666069,
                        "east": -122.37299104724121,
                        "south": 37.62922354964912,
                        "west": -122.47341295275879,
                    },
                    "mapZoom": 14,
                    "isMapVisible": True,
                    "filterState": {
                        "price": {"min": 0, "max": 1250000},
                        "doz": {"value": "7"},
                        "con": {"value": False},
                        "apa": {"value": False},
                        "mp": {"min": 0, "max": 6774},
                        "ah": {"value": True},
                        "sort": {"value": "globalrelevanceex"},
                        "land": {"value": False},
                        "tow": {"value": False},
                        "manu": {"value": False},
                        "apco": {"value": False},
                    },
                    "isListVisible": True,
                    "regionSelection": [{"regionId": 97545, "regionType": 7}],
                },
            },
            {
                "zip_code": 94044,
                "base_url": "https://www.zillow.com/pacifica-ca-94044/?searchQueryState=",
                "search_query": {
                    "usersSearchTerm": "",
                    "mapBounds": {
                        "north": 37.722195621288755,
                        "east": -122.27007868896483,
                        "south": 37.50380920575284,
                        "west": -122.67176631103514,
                    },
                    "mapZoom": 12,
                    "isMapVisible": True,
                    "filterState": {
                        "price": {"min": 0, "max": 1250000},
                        "doz": {"value": "7"},
                        "con": {"value": False},
                        "apa": {"value": False},
                        "mp": {"min": 0, "max": 6774},
                        "ah": {"value": True},
                        "sort": {"value": "globalrelevanceex"},
                        "land": {"value": False},
                        "tow": {"value": False},
                        "manu": {"value": False},
                        "apco": {"value": False},
                    },
                    "isListVisible": True,
                    "regionSelection": [{"regionId": 97531, "regionType": 7}],
                    "pagination": {},
                },
            },
            {
                "zip_code": 94066,
                "base_url": "https://www.zillow.com/san-bruno-ca-94066/?searchQueryState=",
                "search_query": {
                    "usersSearchTerm": "",
                    "mapBounds": {
                        "north": 37.642316,
                        "east": -122.39635,
                        "south": 37.599678,
                        "west": -122.472706,
                    },
                    "mapZoom": 14,
                    "isMapVisible": True,
                    "filterState": {
                        "price": {"min": 0, "max": 1250000},
                        "doz": {"value": "7"},
                        "con": {"value": False},
                        "apa": {"value": False},
                        "mp": {"min": 0, "max": 6774},
                        "ah": {"value": True},
                        "sort": {"value": "globalrelevanceex"},
                        "land": {"value": False},
                        "tow": {"value": False},
                        "manu": {"value": False},
                        "apco": {"value": False},
                    },
                    "isListVisible": True,
                    "regionSelection": [{"regionId": 97540, "regionType": 7}],
                    "pagination": {},
                },
            },
            {
                "zip_code": 94128,
                "base_url": "https://www.zillow.com/ca-94128/?searchQueryState=",
                "search_query": {
                    "usersSearchTerm": "",
                    "mapBounds": {
                        "north": 37.648133,
                        "east": -122.355015,
                        "south": 37.604772,
                        "west": -122.404009,
                    },
                    "mapZoom": 14,
                    "isMapVisible": True,
                    "filterState": {
                        "price": {"min": 0, "max": 1250000},
                        "doz": {"value": "7"},
                        "con": {"value": False},
                        "apa": {"value": False},
                        "mp": {"min": 0, "max": 6774},
                        "ah": {"value": True},
                        "sort": {"value": "globalrelevanceex"},
                        "land": {"value": False},
                        "tow": {"value": False},
                        "manu": {"value": False},
                        "apco": {"value": False},
                    },
                    "isListVisible": True,
                    "regionSelection": [{"regionId": 97582, "regionType": 7}],
                    "pagination": {},
                },
            },
            {
                "zip_code": 94030,
                "base_url": "https://www.zillow.com/pacifica-ca-94030/?searchQueryState=",
                "search_query": {
                    "usersSearchTerm": "",
                    "mapBounds": {
                        "north": 37.62694191021047,
                        "east": -122.3583560472412,
                        "south": 37.572335428783354,
                        "west": -122.45877795275878,
                    },
                    "mapZoom": 14,
                    "isMapVisible": True,
                    "filterState": {
                        "price": {"min": 0, "max": 1250000},
                        "doz": {"value": "7"},
                        "con": {"value": False},
                        "apa": {"value": False},
                        "mp": {"min": 0, "max": 6774},
                        "ah": {"value": True},
                        "sort": {"value": "globalrelevanceex"},
                        "land": {"value": False},
                        "tow": {"value": False},
                        "manu": {"value": False},
                        "apco": {"value": False},
                    },
                    "isListVisible": True,
                    "regionSelection": [{"regionId": 97521, "regionType": 7}],
                    "pagination": {},
                },
            },
            {
                "zip_code": 94010,
                "base_url": "https://www.zillow.com/burlingame-ca-94010/?searchQueryState=",
                "search_query": {
                    "usersSearchTerm": "",
                    "mapBounds": {
                        "north": 37.6107967823491,
                        "east": -122.27958409448242,
                        "south": 37.5015200535949,
                        "west": -122.48042790551757,
                    },
                    "mapZoom": 13,
                    "isMapVisible": True,
                    "filterState": {
                        "price": {"min": 0, "max": 1250000},
                        "doz": {"value": "7"},
                        "con": {"value": False},
                        "apa": {"value": False},
                        "mp": {"min": 0, "max": 6774},
                        "ah": {"value": True},
                        "sort": {"value": "globalrelevanceex"},
                        "land": {"value": False},
                        "tow": {"value": False},
                        "manu": {"value": False},
                        "apco": {"value": False},
                    },
                    "isListVisible": True,
                    "regionSelection": [{"regionId": 97501, "regionType": 7}],
                    "pagination": {},
                },
            },
            {
                "zip_code": 94401,
                "base_url": "https://www.zillow.com/san-mateo-ca-94401/?searchQueryState=",
                "search_query": {
                    "usersSearchTerm": "",
                    "mapBounds": {
                        "north": 37.60380036751255,
                        "east": -122.26752754724123,
                        "south": 37.5491768996272,
                        "west": -122.36794945275881,
                    },
                    "mapZoom": 14,
                    "isMapVisible": True,
                    "filterState": {
                        "price": {"min": 0, "max": 1250000},
                        "doz": {"value": "7"},
                        "con": {"value": False},
                        "apa": {"value": False},
                        "mp": {"min": 0, "max": 6774},
                        "ah": {"value": True},
                        "sort": {"value": "globalrelevanceex"},
                        "land": {"value": False},
                        "tow": {"value": False},
                        "manu": {"value": False},
                        "apco": {"value": False},
                    },
                    "isListVisible": True,
                    "regionSelection": [{"regionId": 97701, "regionType": 7}],
                    "pagination": {},
                },
            },
            {
                "zip_code": 94404,
                "base_url": "https://www.zillow.com/san-mateo-ca-94404/?searchQueryState=",
                "search_query": {
                    "usersSearchTerm": "",
                    "mapBounds": {
                        "north": 37.57563,
                        "east": -122.245156,
                        "south": 37.533427,
                        "west": -122.294439,
                    },
                    "mapZoom": 14,
                    "isMapVisible": True,
                    "filterState": {
                        "price": {"min": 0, "max": 1250000},
                        "doz": {"value": "7"},
                        "con": {"value": False},
                        "apa": {"value": False},
                        "mp": {"min": 0, "max": 6774},
                        "ah": {"value": True},
                        "sort": {"value": "globalrelevanceex"},
                        "land": {"value": False},
                        "tow": {"value": False},
                        "manu": {"value": False},
                        "apco": {"value": False},
                    },
                    "isListVisible": True,
                    "regionSelection": [{"regionId": 97704, "regionType": 7}],
                    "pagination": {},
                },
            },
            {
                "zip_code": 94403,
                "base_url": "https://www.zillow.com/san-mateo-ca-94403/?searchQueryState=",
                "search_query": {
                    "usersSearchTerm": "",
                    "mapBounds": {
                        "north": 37.56865526726825,
                        "east": -122.25352854724119,
                        "south": 37.51400601908233,
                        "west": -122.35395045275877,
                    },
                    "mapZoom": 14,
                    "isMapVisible": True,
                    "filterState": {
                        "price": {"min": 0, "max": 1250000},
                        "doz": {"value": "7"},
                        "con": {"value": False},
                        "apa": {"value": False},
                        "mp": {"min": 0, "max": 6774},
                        "ah": {"value": True},
                        "sort": {"value": "globalrelevanceex"},
                        "land": {"value": False},
                        "tow": {"value": False},
                        "manu": {"value": False},
                        "apco": {"value": False},
                    },
                    "isListVisible": True,
                    "regionSelection": [{"regionId": 97703, "regionType": 7}],
                    "pagination": {},
                },
            },
            {
                "zip_code": 94402,
                "base_url": "https://www.zillow.com/san-mateo-ca-94402/?searchQueryState=",
                "search_query": {
                    "usersSearchTerm": "",
                    "mapBounds": {
                        "north": 37.592560892228896,
                        "east": -122.23414709448241,
                        "south": 37.4832574074068,
                        "west": -122.43499090551757,
                    },
                    "mapZoom": 13,
                    "isMapVisible": True,
                    "filterState": {
                        "price": {"min": 0, "max": 1250000},
                        "doz": {"value": "7"},
                        "con": {"value": False},
                        "apa": {"value": False},
                        "mp": {"min": 0, "max": 6774},
                        "ah": {"value": True},
                        "sort": {"value": "globalrelevanceex"},
                        "land": {"value": False},
                        "tow": {"value": False},
                        "manu": {"value": False},
                        "apco": {"value": False},
                    },
                    "isListVisible": True,
                    "regionSelection": [{"regionId": 97702, "regionType": 7}],
                    "pagination": {},
                },
            },
        ],
    }
}
